my_blog/article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('article-list/',views.article_list,name='article_list'),
    path('article-detail/<int:id>/',views.article_detail,name='article_detail'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls',namespace='article')),
]

my_blog/article/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

from django.utils import timezone


class ArticlePost(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)

    title = models.CharField(max_length = 100)

    body = models.TextField()

    created = models.DateTimeField(default=timezone.now)

    updated = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return self.title

my_blog/article/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

from .models import ArticlePost

import markdown

def article_list(request):
    articles = ArticlePost.objects.all()

    context = {'articles' : articles}

    return render(request,'article/list.html', context)


def article_detail(request,id):
    article = ArticlePost.objects.get(id=id)

    article.body = markdown.markdown(article.body,
        extensions =[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        ]
        )

    context = {'article':article}

    return render(request,'article/detail.html',context)

my_blog/templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
        <div class="col-12 alert alert-success">作者：{{ article.author }}</div>
        <!-- 文章正文 -->
        <div class="col-12">
            <p>{{ article.body |safe }}</p>
        </div>
    </div>
</div>

{% endblock content %}

my_blog/templates/article/list.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <div class="row mt-2">

        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock content %}

my_blog/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{%endblock%}</title>
    <link rel="stylesheet" href="{%static 'bootstrap/css/boostrap.min.css'}">
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
  </head>
  <body>
    {% include 'header.html' %}
    {% block content %} {% endblock content %}
    {% include 'footer.html' %}
    <script src="{% static 'jquery/jquery.js' %}">

    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>

    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

my_blog/templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.dusaiphoto.com 2018</p>
    </div>
</footer>

my_blog/templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="#">我的博客</a>

    <!-- 导航入口 -->
    <div>
      <ul class="navbar-nav">
        <!-- 条目 -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
        </li>
      </ul>
    </div>

  </div>
</nav>